MidCamp/midcamp

- composer.json
This changes composer to use the Drupal.org packagist https://www.drupal.org/node/2718229.
> Use Drupal.org packagist

- conf/drupal/config/core.base_field_override.node.job.promote.yml
- conf/drupal/config/core.entity_form_display.node.job.default.yml
- conf/drupal/config/core.entity_view_display.node.job.default.yml
- conf/drupal/config/core.entity_view_display.node.job.teaser.yml
- conf/drupal/config/field.field.node.job.field_job_description.yml
- conf/drupal/config/field.field.node.job.field_job_link.yml
- conf/drupal/config/field.field.node.job.field_job_location.yml
- conf/drupal/config/field.field.node.job.field_job_skill_level.yml
- conf/drupal/config/field.field.node.job.field_job_type.yml
- conf/drupal/config/field.storage.node.field_job_description.yml
- conf/drupal/config/field.storage.node.field_job_link.yml
- conf/drupal/config/field.storage.node.field_job_location.yml
- conf/drupal/config/field.storage.node.field_job_skill_level.yml
- conf/drupal/config/field.storage.node.field_job_type.yml
- conf/drupal/config/node.type.job.yml
Exported content type config: job
> ericjenkins: Created Job Content Type.

- features/bootstrap/DrupalFieldContext.php
Replicating Joe's DrupalFieldContext.php fix on 2 other lines
> Feature ej 20160820 jobs content type

- README.md
- build.xml
- circle.yml
- conf/build.circle.properties
- features/article.feature
- features/bootstrap/DrupalFieldContext.php
- features/job.feature
- features/sponsor.feature
- package.json
If there's a little green checkmark for CircleCI, it's good.
> Build and test on CircleCI

- .codeclimate.yml
- .phpmd.xml
- README.md
- build.xml
- composer.json
- composer.lock
- features/bootstrap/DrupalFieldContext.php
- features/bootstrap/FeatureContext.php
@todo add things for the theme (this is probably a follow up, yes?)
Things to validate with this PR:
1. That codeclimate sees the config
1. That the errors codeclimate shows are sensible
> Add code climate config

- behat.yml
- features/bootstrap/FailureContext.php
- features/failures/.gitignore
Takes a screenshot or html dump of page on failed step.
> Adds Failure context and failure directory.

- README.md
- features/bootstrap/FailureContext.php
This adds the Code Climate badge to the readme.
> Add Code Climate badge to readme

- conf/drupal/config/core.base_field_override.node.topic.promote.yml
- conf/drupal/config/core.base_field_override.node.topic.status.yml
- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/core.entity_view_display.node.topic.default.yml
- conf/drupal/config/core.entity_view_display.node.topic.teaser.yml
- conf/drupal/config/field.field.node.topic.body.yml
- conf/drupal/config/field.field.node.topic.field_event.yml
- conf/drupal/config/field.field.node.topic.field_people.yml
- conf/drupal/config/field.field.node.topic.field_topic_type.yml
- conf/drupal/config/field.storage.node.field_event.yml
- conf/drupal/config/field.storage.node.field_people.yml
- conf/drupal/config/field.storage.node.field_topic_type.yml
- conf/drupal/config/node.type.topic.yml
- conf/drupal/config/taxonomy.vocabulary.topic_type.yml
- features/topic.feature
Add config for topic content type
> 23 Topic content type

- provisioning/roles/common/tasks/main.yml
Link to issue on Trello:
https://trello.com/c/7wmbVw1m/45-fix-ansible-provisioning-error-during-initial-vagrant-up-process
> Attempting to fix Ansible provisioning error.

- composer.json
- composer.lock
- conf/drupal/config/core.entity_form_display.taxonomy_term.event.default.yml
- conf/drupal/config/core.entity_view_display.node.topic.teaser.yml
- conf/drupal/config/core.entity_view_display.taxonomy_term.event.default.yml
- conf/drupal/config/core.extension.yml
- conf/drupal/config/field.field.taxonomy_term.event.field_date.yml
- conf/drupal/config/field.field.taxonomy_term.event.field_social_media.yml
- conf/drupal/config/field.storage.taxonomy_term.field_date.yml
- conf/drupal/config/field.storage.taxonomy_term.field_social_media.yml
- conf/drupal/config/taxonomy.vocabulary.event.yml
- features/event.feature
Completes the data structures for https://trello.com/c/widFAAgv/24-event
- composer install
- build
- visit http://midcamp.local/admin/structure/taxonomy/manage/event/add
> 24-Event Taxonomy

- composer.json
- composer.lock
- conf/drupal/config/core.entity_form_display.contact_message.feedback.default.yml
- conf/drupal/config/core.entity_form_display.paragraph.contact_form.default.yml
- conf/drupal/config/core.entity_form_display.paragraph.paragraphs_columns_uneven_2.default.yml
- conf/drupal/config/core.entity_form_display.paragraph.view.default.yml
- conf/drupal/config/core.entity_view_display.contact_message.feedback.default.yml
- conf/drupal/config/core.entity_view_display.paragraph.contact_form.default.yml
- conf/drupal/config/core.entity_view_display.paragraph.paragraphs_columns_uneven_2.default.yml
- conf/drupal/config/core.entity_view_display.paragraph.view.default.yml
- conf/drupal/config/core.extension.yml
- conf/drupal/config/field.field.node.article.field_article_paragraphs.yml
- conf/drupal/config/field.field.node.page.field_page_paragraphs.yml
- conf/drupal/config/field.field.node.venue.field_venue_paragraphs.yml
- conf/drupal/config/field.field.paragraph.contact_form.field_contact.yml
- conf/drupal/config/field.field.paragraph.paragraphs_columns_uneven_2.field_column_content_2.yml
- conf/drupal/config/field.field.paragraph.paragraphs_columns_uneven_2.field_grid_style.yml
- conf/drupal/config/field.field.paragraph.view.field_view.yml
- conf/drupal/config/field.storage.paragraph.field_column_content_2.yml
- conf/drupal/config/field.storage.paragraph.field_contact.yml
- conf/drupal/config/field.storage.paragraph.field_contact_form.yml
- conf/drupal/config/field.storage.paragraph.field_grid_style.yml
- conf/drupal/config/field.storage.paragraph.field_view.yml
- conf/drupal/config/paragraphs.paragraphs_type.contact_form.yml
- conf/drupal/config/paragraphs.paragraphs_type.paragraphs_columns_uneven_2.yml
- conf/drupal/config/paragraphs.paragraphs_type.view.yml
- web/themes/custom/hatter/templates/paragraphs/paragraph--paragraphs-columns-uneven-2.html.twig
Adds more Paragraphs fun to Article, Page, Venue content types.
> Adds and configures Columns (Two Uneven), Contact Form, and View Paragraph bundles.

- Vagrantfile
- provisioning/roles/common/tasks/main.yml
- provisioning/roles/gulp/tasks/main.yml
- provisioning/roles/php/defaults/main.yml
- provisioning/roles/php/tasks/main.yml
- provisioning/roles/vhost/tasks/main.yml
These changes were needed to be able to follow the instructions in the Getting Started section of the root README.md.
> Syncs provisioning files with updated palantir/the-vagrant.

- composer.json
- composer.lock
- conf/drupal/config/core.entity_form_display.node.article.default.yml
- conf/drupal/config/core.entity_view_display.node.article.default.yml
- conf/drupal/config/core.entity_view_display.node.article.rss.yml
- conf/drupal/config/field.field.node.article.field_planet.yml
- conf/drupal/config/field.storage.node.field_planet.yml
- conf/drupal/config/views.view.drupal_planet.yml
- conf/drupal/config/views.view.news.yml
- web/sites/example.settings.local.php
> Add planet field and feed view.

- composer.json
- composer.lock
- conf/drupal/config/core.extension.yml
- conf/drupal/config/google_analytics.settings.yml
Resolves #77.  Adds Google Analytics module, configured with property ID.
- Observe tracking code on site
> Issue #77: Google Analytics

- composer.json
- composer.lock
- conf/drupal/config/core.extension.yml
- conf/drupal/config/r4032login.settings.yml
To test it, while logged out, go to /node/add/topic. Instead of the access denied page, you should hit the login page with an access denied message.
> install r4032login; default settings

- web/themes/custom/hatter/templates/block/block--system-branding-block.html.twig
Adds the register link to the branding
> Home page registration link in branding block

- conf/drupal/config/block.block.views_block__event_sponsors_block_1.yml
- conf/drupal/config/views.view.event_sponsors.yml
- conf/drupal/config/views.view.event_venue.yml
event venue and core sponsors now show sitewide. this will give us headaches later when we try to do 2019 things, but we can fix that later
> Footer views

- conf/drupal/config/field.field.user.user.user_picture.yml
- conf/drupal/config/node.type.topic.yml
- disable preview option for topic content type
- increase dims and filesize for user profile pic
> resolve issue #113

- composer.lock
Pull the new css from hatter for the schedule.
> pull in schedule css

- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/core.entity_view_display.node.topic.default.yml
- conf/drupal/config/core.extension.yml
- conf/drupal/config/field.field.node.topic.field_accepted_confirmed.yml
- conf/drupal/config/field.storage.node.field_accepted_confirmed.yml
- conf/drupal/config/system.action.topic_accept_confirm.yml
- conf/drupal/config/views.view.session_selection.yml
- conf/drupal/config/views.view.sessions.yml
- web/modules/custom/midcamp_vbo/config/install/system.action.topic_accept_confirm.yml
- web/modules/custom/midcamp_vbo/config/schema/midcamp_vbo.schema.yml
- web/modules/custom/midcamp_vbo/midcamp_vbo.info.yml
- web/modules/custom/midcamp_vbo/midcamp_vbo.module
- web/modules/custom/midcamp_vbo/src/Plugin/Action/TopicAcceptConfirm.php
This PR does the following
- adds custom module for vbo action to accept and confirm a topic
- adds admin view with vbo for marking topics as accepted (/admin/sessions-select)
- adds accepted sessions view (/accepted-sessions)
> Confirmed sessions

- composer.json
- composer.lock
- web/.ht.router.php
- web/sites/default/default.settings.php
- web/sites/example.settings.local.php
- web/sites/example.sites.php
Updates Drupal from 8.4 to 8.5.  
Encountered a lot of composer dependency issues consistent with what is detailed at https://www.drupal.org/project/drupal/issues/2943546.  Attempted each of the following unsuccessfully:
- `composer update drupal/core --with-dependencies`
- `composer update drupal/core symfony/config --with-dependencies`
- `composer update drupal/core symfony/* --with-dependencies`
- `composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies `
Per [Berdir's comment](https://www.drupal.org/project/drupal/issues/2943546#comment-12477114) I ended up just manually updating `composer.json` to require `^8.5` and ran `composer update`.  
This updated much more than Drupal core, so I'll test this further before merging.
> Drupal core 8.5.3, other updates.

- .lagoon.yml
When this is merged to `production` dns can be updated.
> minor changes before production production

- .lagoon.yml
Bring these back when static page is taken down.
> Comment out production domains

- .lagoon.yml
Removing domains that don't have DNS pointing to Lagoon yet.
> Merging master into production

- composer.lock
See https://www.drupal.org/SA-CORE-2018-006.
> Update Drupal to 8.6.2

- conf/drupal/config/block.block.views_block__event_sponsors_block_1.yml
- conf/drupal/config/views.view.jobs_board.yml
Jobs Board view, Sponsors Block tweaks from the dev environment.
> Export active config.

- web/themes/custom/hatter/templates/block/block--system-branding-block.html.twig
Comment out the `Register` button and replace with a `Submit a Session` button.
> Change home page branding button

- composer.lock
Includes changes in https://github.com/MidCamp/Hatter/pull/40
> Update Hatter style guide

- web/themes/custom/hatter/templates/block/block--system-branding-block.html.twig
- Updates "Submit a Session" button on homepage to target `/submit-session`
> Link to Submit Session page instead of add topic form

- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/user.role.authenticated.yml
- conf/drupal/config/views.view.sessions.yml
- conf/drupal/config/views.view.sessions_export.yml
- Exports Sessions Export view config changes made in production
- Exports Sessions view updates made in production (updating links for the Topic submission page)
- Adds fields to the Topic entity form display so authors can be changed
- Adds permissions for Restricted HTML text format to authenticated users so they can change their own bio field after creating an account
> Misc config updates

- .amazeeio.yml
- composer.lock
- web/sites/default/default.settings.php
- web/sites/example.sites.php
Updates Drupal core.  Also adds a cache rebuild before attempting config-import, which failed a production deploy on January 7.
> SA-CORE-2019-001, SA-CORE-2019-002

- composer.lock
Per [SA-CORE-2019-003](https://www.drupal.org/sa-core-2019-003), updating:
- Core
- Metatag
- Paragraphs
> SA-CORE-2019-003

- conf/drupal/config/views.view.jobs_board.yml
- conf/drupal/config/views.view.schedule_2019.yml
Manually updated the config... should prob be tested first. Feel free to ditch this if it's just easier to bring it down from prod.
> Add words to job board header

- conf/drupal/config/block.block.addajobbutton.yml
- conf/drupal/config/block.block.eventlabelblock.yml
- conf/drupal/config/block.block.hatter_help.yml
- conf/drupal/config/block.block.hatter_messages.yml
- conf/drupal/config/block.block.hatter_page_title.yml
- conf/drupal/config/block.block.midcamp2019.yml
- conf/drupal/config/block.block.tabs.yml
- conf/drupal/config/block.block.views_block__attendees_block_2.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_6.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_8.yml
- conf/drupal/config/block.block.views_block__summits_block_1.yml
- conf/drupal/config/core.entity_view_display.node.job.default.yml
- Exports config for custom block "Add a Job button"
- Hide event field on Job nodes
> Add jobs button

- conf/drupal/config/block.block.views_block__event_sponsors_block_7.yml
- conf/drupal/config/honeypot.settings.yml
- conf/drupal/config/webform.webform.tourism_quote.yml
- Disables Honeypot on the password reset form, which had been causing unexpected failures
- Exports production config for event sponsor block and Tourism webform
> Update Honeypot, export Prod config

- conf/drupal/config/honeypot.settings.yml
Still getting spammy users.  Upping minimum time to 12 seconds to deter bots.
> Upping honeypot time

- composer.json
- composer.lock
Also apply updated 8.7 patch for https://www.drupal.org/project/drupal/issues/2901418.
> Update Drupal Core to 8.7.1

- conf/drupal/config/block.block.addajobbutton.yml
- conf/drupal/config/block.block.eventlabelblock.yml
- conf/drupal/config/block.block.hatter_content.yml
- conf/drupal/config/block.block.hatter_help.yml
- conf/drupal/config/block.block.hatter_local_actions.yml
- conf/drupal/config/block.block.hatter_messages.yml
- conf/drupal/config/block.block.hatter_page_title.yml
- conf/drupal/config/block.block.midcamp2019.yml
- conf/drupal/config/block.block.tabs.yml
- conf/drupal/config/block.block.training_feedback_form.yml
- conf/drupal/config/block.block.views_block__attendees_block_2.yml
- conf/drupal/config/block.block.views_block__event_news_block_1.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_10.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_11.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_2.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_3.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_4.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_5.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_6.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_7.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_8.yml
- conf/drupal/config/block.block.views_block__event_sponsors_block_9.yml
- conf/drupal/config/block.block.views_block__jobs_board_block_1.yml
- conf/drupal/config/block.block.webform.yml
- conf/drupal/config/node.type.page.yml
- conf/drupal/config/views.view.event_sponsors.yml
Exports some configuration performed manually on the production site.
> Export updated page config from production.

- composer.json
- composer.lock
- conf/drupal/config/core.extension.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.article.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.job.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.page.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.sponsor.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.summit.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.topic.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.training.yml
- conf/drupal/config/simple_sitemap.bundle_settings.default.node.venue.yml
- conf/drupal/config/simple_sitemap.custom_links.default.yml
- conf/drupal/config/simple_sitemap.settings.yml
- conf/drupal/config/simple_sitemap.variants.default_hreflang.yml
- Adds [Simple XML Sitemap](https://www.drupal.org/project/simple_sitemap)
- Enables Simple XML Sitemap, exports basic config
- Enables indexing on content types
> Simple XML Sitemap

- README.md
- Pygmy docs moved, so updating the link
- add how to tear it all down.
> Update links and how to stop.

- composer.lock
From https://github.com/MidCamp/Hatter/pull/44
> Update Hatter for sponsor fix.

- .circleci/config.yml
- Dockerfile.cli
- README.md
- web/themes/custom/hatter_2019/package-lock.json
- web/themes/custom/hatter_2019/package.json
Branched off of feature/fix-circle.
Updates hatter_2019 theme to latest version of hatter NPM module so things look more green.
> Updated Hatter 2019 to use Green Colors

- composer.lock
Updates Drupal Core for today's security releases.  
Test this remotely at https://nginx-midcamp-org-feature-drupal-core-updates.us.amazee.io/
> Update Drupal core.

- conf/drupal/config/captcha.captcha_point.user_register_form.yml
- conf/drupal/config/captcha.settings.yml
- conf/drupal/config/contact.settings.yml
- conf/drupal/config/recaptcha.settings.yml
- conf/drupal/config/user.settings.yml
- conf/drupal/config/views.view.sessions.yml
- conf/drupal/config/views.view.sessions_export.yml
- 2020 session views
- lock down user profiles
- tighten captcha
> capture live config

- web/themes/custom/hatter_base/templates/block/block--system-branding-block.html.twig
Seems this is the place to hide session submissions and reveal the ticket link.
> add the ticket link to the correct template

- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/core.entity_view_display.node.attendee.teaser.yml
- conf/drupal/config/core.entity_view_display.taxonomy_term.event.default.yml
- web/themes/custom/hatter_base/templates/block/block--system-menu-block.html.twig
- web/themes/custom/hatter_base/templates/page/page--front.html.twig
- web/themes/custom/hatter_base/templates/page/page.html.twig
Leveraging styles from https://midcamp.github.io/Hatter/components/news-teaser/, this is a temporary hard-coded news teaser until something more permanent can be built.
> Hardcoded MidCamp News Alert

- conf/drupal/config/block.block.hatter_2019_addajobbutton.yml
- conf/drupal/config/block.block.hatter_2019_content.yml
- conf/drupal/config/block.block.hatter_2019_eventlabelblock.yml
- conf/drupal/config/block.block.hatter_2019_help.yml
- conf/drupal/config/block.block.hatter_2019_local_actions.yml
- conf/drupal/config/block.block.hatter_2019_messages.yml
- conf/drupal/config/block.block.hatter_2019_midcamp2019.yml
- conf/drupal/config/block.block.hatter_2019_page_title.yml
- conf/drupal/config/block.block.hatter_2019_tabs.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_news_block_1.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_10.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_11.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_2.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_3.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_4.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_5.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_6.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_7.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_8.yml
- conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_9.yml
- conf/drupal/config/block.block.hatter_2019_views_block__jobs_board_block_1.yml
- conf/drupal/config/block.block.hatter_2019_views_block__speakers_block_1.yml
- conf/drupal/config/block.block.hatter_2019_views_block__summits_block_1.yml
- conf/drupal/config/block.block.hatter_2019_views_block__training_block_1.yml
- conf/drupal/config/block.block.hatter_2019_webform.yml
- conf/drupal/config/block.block.views_block__attendees_2020_block_1.yml
- conf/drupal/config/block.block.views_block__live_sessions_block_1.yml
- conf/drupal/config/block.block.views_block__random_session_block_1.yml
- conf/drupal/config/views.view.live_sessions.yml
> Live Session Homepage Block

- README.md
Adding info on how feature environments work. @Brian-Clement feel free to correct anything that's not quite right.
> Add info to README on feature environments

- conf/drupal/config/views.view.session_feedback.yml
Imported config from production.
> Add block description and empty text

- composer.lock
- conf/drupal/config/user.settings.yml
- Production config export
- Drupal Core 8.8.8 upgrade
> Drupal 8.8.8

- .lagoon.yml
Per Tyler's and https://docs.lagoon.sh/lagoon/using-lagoon-the-basics/lagoon-yml#ssl-configuration-tls-acme
> Set tls-acme to false

- composer.lock
Updates Drupal Core to 8.9.13 per [SA-CORE-2021-001](https://www.drupal.org/sa-core-2021-001)
> Update Drupal core per SA-CORE-2021-001.

- composer.lock
Updates Drupal Core for [SA-CORE-2021-002](https://www.drupal.org/sa-core-2021-002).
> Update Drupal core for SA-CORE-2021-002.

- composer.lock
- Updates CTools to 8.x-3.7 for SA-CONTRIB-2021-015
- Updates Drupal Core to 8.9.17 for SA-CORE-2021-004
> SA-CORE-2021-004, SA-CONTRIB-2021-015

- composer.lock
Updates Drupal Core to 8.9.18 for [SA-CORE-2021-005](https://www.drupal.org/sa-core-2021-005).
> SA-CORE-2021-005: Drupal Core 8.9.18

- composer.lock
> Deploying to production

- composer.lock
- conf/drupal/config/core.extension.yml
- conf/drupal/config/system.action.webform_archive_action.yml
- conf/drupal/config/system.action.webform_close_action.yml
- conf/drupal/config/system.action.webform_delete_action.yml
- conf/drupal/config/system.action.webform_open_action.yml
- conf/drupal/config/system.action.webform_unarchive_action.yml
- conf/drupal/config/webform.settings.yml
Updates Admin Toolbar to 2.5 for SA-CONTRIB-2021-025, Webform to 5.28 for SA-CONTRIB-2021-026.
> SA-CONTRIB-2021-025, SA-CONTRIB-2021-026.

- composer.lock
Updates Drupal Core to 8.9.19 to address the following security advisories:
- [SA-CORE-2021-006](https://www.drupal.org/sa-core-2021-006)
- [SA-CORE-2021-007](https://www.drupal.org/sa-core-2021-007)
- [SA-CORE-2021-008](https://www.drupal.org/sa-core-2021-008)
- [SA-CORE-2021-009](https://www.drupal.org/sa-core-2021-009)
- [SA-CORE-2021-010](https://www.drupal.org/sa-core-2021-010)
- Install dependencies via `lando composer install`
- Confirm there are no database updates via `lando drush updb -y`
- Confirm the site is upgraded to 8.9.19
> Drupal 8.9.19

- composer.lock
- conf/drupal/config/system.site.yml
- conf/drupal/config/webform.webform.midcamp_2021_feedback_survey.yml
- Exports config from Production environment
- Updates Drupal Core to 8.9.20 for [SA-CORE-2021-011](https://www.drupal.org/sa-core-2021-011)
- Updates Webform to 5.29.0
> Drupal Core 

- rector.php
Adds rector.php file, previously omitted in #431
> Adds rector.php.

- composer.lock
Updates Drupal Core to 9.3.14 for [SA-CORE-2022-010](https://www.drupal.org/sa-core-2022-010)
> Update Drupal Core for SA-CORE-2022-010.

- composer.lock
- conf/drupal/config/editor.editor.basic_html.yml
- conf/drupal/config/editor.editor.full_html.yml
- Updates Drupal Core to 9.4.8
- Exports updated config for CKEditor after `omit_settings_for_disabled_plugins` update
> Drupal 9.4.8.

- conf/drupal/config/webform.webform.lightning_talk_sign_up.yml
- conf/drupal/config/webform.webform.midcamp_2018_survey.yml
- conf/drupal/config/webform.webform.midcamp_2019_survey.yml
- conf/drupal/config/webform.webform.midcamp_2021_survey.yml
- conf/drupal/config/webform.webform.midcamp_2023_interest.yml
- conf/drupal/config/webform.webform.movie_suggestions.yml
- conf/drupal/config/webform.webform.session_feedback.yml
- conf/drupal/config/webform.webform.tourism_quote.yml
- conf/drupal/config/webform.webform.training_feedback.yml
- conf/drupal/config/webform.webform.training_feedback_2019.yml
Closes many webforms.  Creates MidCamp 2023 Interest webform.
> Export produciton config.

- conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_10.yml
- conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_3.yml
- conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_9.yml
- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/dblog.settings.yml
- conf/drupal/config/editor.editor.basic_html.yml
- conf/drupal/config/filter.format.basic_html.yml
- conf/drupal/config/recaptcha.settings.yml
- conf/drupal/config/user.settings.yml
- conf/drupal/config/views.view.news.yml
- conf/drupal/config/views.view.sessions.yml
Exports configuration changes made directly in Production.
> Export production config changes.

- composer.json
- composer.lock
- conf/drupal/config/core.extension.yml
- conf/drupal/config/quick_node_clone.settings.yml
Pull request for https://github.com/MidCamp/midcamp/issues/390
> 390 Installed and enabled Quick Node Clone module

- conf/drupal/config/views.view.schedule_2023.yml
Exports latest config from Production.
> Export updated 2023 schedule config.

- web/themes/custom/hatter/templates/block/block--system-branding-block.html.twig
https://www.drupal.org/project/midcamp/issues/3359260
> #481 D.o issue 3359260: Comment out Register button in Theme code

- conf/drupal/config/block.block.midcamp2023survey.yml
- conf/drupal/config/field.field.node.topic.field_event.yml
- conf/drupal/config/node.type.page.yml
- conf/drupal/config/system.menu.midcamp-2024-navigation.yml
- conf/drupal/config/user.role.authenticated.yml
- conf/drupal/config/user.settings.yml
Exports production config as of 24 October.
1. Import configuration with `lando drush cim -y`
2. Confirm the configuration matches the production environment
> Production config export October 24

- conf/drupal/config/block.block.midcamp2023navigation.yml
- conf/drupal/config/block.block.midcamp2024navigation.yml
- conf/drupal/config/system.site.yml
- conf/drupal/config/views.view.news.yml
- conf/drupal/config/views.view.organizers.yml
- conf/drupal/config/views.view.sessions.yml
- conf/drupal/config/views.view.sponsor_company_field_filter.yml
- web/modules/custom/midcamp_utility/midcamp_utility.module
- web/themes/custom/hatter/hatter.theme
- web/themes/custom/hatter_base/hatter_base.theme
- Exports basic config changes necessary for the new Camp year
1. Import configuration with `lando drush cim -y`
2. Rebuild caches with `lando drush cr`
3. TBD
> Midcamp 2024

- conf/drupal/config/captcha.captcha_point.contact_message_feedback_form.yml
- conf/drupal/config/captcha.captcha_point.contact_message_personal_form.yml
- conf/drupal/config/captcha.captcha_point.node_article_form.yml
- conf/drupal/config/captcha.captcha_point.node_eventbrite_event_form.yml
- conf/drupal/config/captcha.captcha_point.node_job_form.yml
- conf/drupal/config/captcha.captcha_point.node_page_form.yml
- conf/drupal/config/captcha.captcha_point.node_sponsor_form.yml
- conf/drupal/config/captcha.captcha_point.node_summit_form.yml
- conf/drupal/config/captcha.captcha_point.node_topic_form.yml
- conf/drupal/config/captcha.captcha_point.node_training_form.yml
- conf/drupal/config/captcha.captcha_point.node_venue_form.yml
- conf/drupal/config/captcha.captcha_point.user_login_form.yml
- conf/drupal/config/captcha.captcha_point.user_pass.yml
- conf/drupal/config/core.entity_form_display.node.topic.default.yml
- conf/drupal/config/pathauto.pattern.basic_pages.yml
- conf/drupal/config/pathauto.pattern.content.yml
- conf/drupal/config/pathauto.pattern.jobs.yml
- conf/drupal/config/r4032login.settings.yml
- conf/drupal/config/simple_sitemap.settings.yml
- conf/drupal/config/system.action.comment_delete_action.yml
- conf/drupal/config/system.action.node_delete_action.yml
- conf/drupal/config/views.view.redirect.yml
- conf/drupal/config/views.view.schedule_2024.yml
- conf/drupal/config/views.view.scheduler_scheduled_content.yml
- conf/drupal/config/webform.settings.yml
- fixed the accepted sessions view
- exported config so that the bulk ops fix doesn't get overwritten
> fix: Export config after updb

- web/themes/custom/hatter/port-to-hatter-v2.css
resolves https://www.drupal.org/project/midcamp/issues/3427763
> Add to shame.css - schedule heading cleanup

- web/modules/custom/midcamp_utility/midcamp_utility.module
- web/themes/custom/hatter/hatter.theme
As per https://github.com/MidCamp/midcamp/wiki/Preparing-MidCamp.org-for-a-new-event-year
> Update code for 2025

- web/themes/custom/hatter_base/templates/navigation/menu--main.html.twig
https://www.drupal.org/project/midcamp/issues/3464582
> fix: Ignore missing svgs

- web/themes/custom/hatter_2019/package-lock.json
- web/themes/custom/hatter_2019/package.json
`watch` still has issues, but the main stuff works.
> fix: Update npm dependencies so that 2019 compiles
