build.xml, build/styleguide.xml, conf/build.default.properties
This should now copy css, images and whatnot from the styleguide into the hatter theme when `vendor/bin/phing build` is run.
=> Links the styleguide to the theme

build.xml, build/madcamp.xml, composer.json, composer.lock, conf/build.default.properties
This PR is against the `deploy-to-pantheon` branch from PR #32.
Depends on this PR: https://github.com/palantirnet/the-build/pull/44 (the branch is included in this work).
To test:
* `composer install`
* `vendor/bin/phing deploy -Dbuild.env=default -Dpush=n`
The one thing that's probably going to be weird about this is that I've put the conf directory within Pantheon's `private` directory. This means your `settings.php` will have to reference it in that location:
```php
$config_directories[CONFIG_SYNC_DIRECTORY] = 'private/conf/drupal/config';
```
You can set this via the `drupal.config_sync_directory` phing property as well -- normally on our sites this value is `../conf/drupal/config`, which means our usual `settings.php` files will say:
```php
$config_directories[CONFIG_SYNC_DIRECTORY] …
```
=> Add composer-install-elsewhere to the Pantheon deployment

web/themes/custom/hatter/hatter.libraries.yml
Solves a problem caused by yaml syntax.
``` ID         :  65                                                                                                                                                             
Date       :  02/Apr 16:06                                                                                                                                                   
Type       :  php                                                                                                                                                            
Severity   :  error                                                                                                                                                          
Message    : …
```
=> Fix error w/ yaml parsing in libraries 

web/themes/custom/hatter/templates/block/block--system-branding-block.html.twig
The "Register" button in the header didn't go anywhere. Let's hide this until we can make it useful.
=> Hide header button until we have something to do with it.

web/themes/custom/hatter/hatter.libraries.yml
Resolves #78.  The map on the homepage is failing to display for anonymous users, throwing error `Uncaught ReferenceError: jQuery is not defined` in `map.js`. 
This PR adds dependencies for `mapbox` to resolve.
- `drush cr`
- Observe the map displays while logged out
=> Issue #78: Add dependencies for mapbox

conf/drupal/config/block.block.hatter_content.yml, conf/drupal/config/block.block.hatter_help.yml, conf/drupal/config/block.block.hatter_local_actions.yml, conf/drupal/config/block.block.tabs.yml, conf/drupal/config/block.block.views_block__event_news_block_1.yml, conf/drupal/config/core.extension.yml, web/themes/custom/hatter/hatter.info.yml
Add tabs back to content region and switch to classy as base theme so we don't have to style every damn ui piece. Also uninstalled workbench tabs to remove tab duplication in the admin theme.
=> change base theme to classy and add tab block to content region

web/themes/custom/hatter/hatter.info.yml, web/themes/custom/hatter/hatter.libraries.yml, web/themes/custom/hatter/templates/block/block--system-menu-block.html.twig, web/themes/custom/hatter/templates/navigation/menu--main.html.twig, web/themes/custom/hatter/templates/page/page.html.twig
This hooks up a single level mobile menu per the style guide. The style guide also includes (and we will need) child menus, but I'm too new to D8 to hook that up yet.
Marking as WIP, but until we have child pages, this is also ready for review.
To test, reduce the width of your browser window until the hamburger menu appears. Clicking on it will expose the full menu.
=> Mobile menu

conf/drupal/config/core.entity_view_display.node.sponsor.default.yml, conf/drupal/config/node.type.sponsor.yml, web/themes/custom/hatter/templates/content/node--sponsor--full.html.twig, web/themes/custom/hatter/templates/field/field--node--field-image--sponsor.html.twig, web/themes/custom/hatter/templates/field/field--node--field-sponsor-level--sponsor.html.twig, web/themes/custom/hatter/templates/field/field--node--title--sponsor.html.twig
Template files and sponsor content type config for cleaning up the sponsor page presentation. 
**This depends on the latest hatter css**
To test, pull a copy of the prod db, where I'm adding unpublished sponsor nodes. Just publish them and they should look similar to the pic below. A couple notes: 
- the sponsor node content is 66% width of the page, allowing for eventual jobs view block on the right
- sponsor logo will occupy 50% of the node content width and is constrained to 16:9 ratio
=> Unfugly sponsor pages

conf/drupal/config/block.block.hatter_branding.yml, web/themes/custom/hatter/templates/block/block--hatter-account-menu.html.twig, web/themes/custom/hatter/templates/layout/html.html.twig, web/themes/custom/hatter/templates/navigation/menu--main.html.twig, web/themes/custom/hatter/templates/page/page--front.html.twig
We all love the hatter, but once off the home page, we need to not scroll down a whole screen to see content.
- **this depends on the latest hatter css**
- adds classing to the body tag for admin role and whether we are on the front page
- adds camp dates to the left side of the mobile menu
- fixes markup around the header bits on the front page
To test:
- go to any page besides the home page and verify the giant hatter/pic is gone
- add menu links to the main menu (Log in - /user/login; Log out - /user/logout) and verify they only show when the mobile hamburger menu is active
=> Internal pages

conf/drupal/config/core.entity_form_display.user.user.default.yml, conf/drupal/config/core.entity_view_display.user.user.default.yml, conf/drupal/config/core.entity_view_display.user.user.featured_speaker.yml, conf/drupal/config/field.field.user.user.field_company_logo.yml, conf/drupal/config/field.storage.user.field_company_logo.yml
- Adds `field_company_logo` to the User profile
- Uses `featured_speaker` image style to display user image, company logo on user entity default display
- Hides field label for `field_company_logo` on user entity default display
- Navigate to a User, observe the company logo field exists
I had permissions issues in the image directory for the new field initially.  I had to `chmod` inside my Vagrant to resolve, but IIRC this is just an issue locally.
=> User profile company logo

conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.node.training.default.yml, conf/drupal/config/core.entity_view_display.user.user.compact.yml, web/themes/custom/hatter/hatter.theme, web/themes/custom/hatter/templates/field/field--user--field-name--compact.html.twig, web/themes/custom/hatter/templates/field/field--user--field-organization--compact.html.twig, web/themes/custom/hatter/templates/field/field--user--field-title--compact.html.twig, web/themes/custom/hatter/templates/user/user--compact.html.twig
- Updates "Compact" view display on User entities to include basic fields:
- Picture
- Name
- Job Title
- Organization
- About Me
- Renders User entity w/"Compact" view mode in Topic, Training nodes
- Updates preprocessing, template suggestions for use in Compact view mode
- Template files for cleaner markup
- View Topic nodes.  Observe the new treatment for Speaker display
- View Session nodes.  Observe the new treatment for Speaker display
Not sure if these are looking quite right at the moment.  Would definitely like some feedback on how to improve.  Also looking for thoughts on how best to incorporate the company logo here.
For Training nodes, I left the speakers at the top:
For Topic nodes, I moved the speakers to the bottom:
=> Add Speaker Bios to Session, Training nodes

conf/drupal/config/system.action.user_add_role_action.organizer.yml, conf/drupal/config/system.action.user_remove_role_action.organizer.yml, conf/drupal/config/user.role.organizer.yml, conf/drupal/config/views.view.organizers.yml
Satisfies ["organizers page" requirement](https://docs.google.com/document/d/1WBe3lO-6nPO0i5yfXNNujQMLJ4XGEui3Plh4bcAJwDk/edit#).
- Creates user role `organizer`
- Creates View `organizers` with Page display at path `/organizers`
- Navigate to the [People admin page](http://midcamp.org.docker.amazee.io/admin/people).  Randomly select some users and select the Action `Add the Organizer role to the selected user(s)`.
- Navigate to the [Organizers page](http://midcamp.org.docker.amazee.io/organizers).  Observe your users with the `organizer` role are now displaying
I set this up as a basic view page with a grid.  I am targeting the "Featured Speaker" view mode for User entities.  Do we have any preference on what this should look like?  I made these …
=> Organizers Page

composer.json, composer.lock, conf/drupal/config/core.entity_form_display.media.video.default.yml, conf/drupal/config/core.entity_form_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.media.video.default.yml, conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/core.extension.yml, conf/drupal/config/field.field.media.video.field_media_video_embed_field.yml, conf/drupal/config/field.field.node.topic.field_video.yml, conf/drupal/config/field.storage.media.field_media_video_embed_field.yml, conf/drupal/config/field.storage.node.field_video.yml, conf/drupal/config/media_entity.bundle.video.yml, conf/drupal/config/media_entity.settings.yml, conf/drupal/config/system.action.media_delete_action.yml, conf/drupal/config/system.action.media_publish_action.yml, conf/drupal/config/system.action.media_save_action.yml, conf/drupal/config/system.action.media_unpublish_action.yml, conf/drupal/config/views.view.media.yml
Satisfies ["@TODO: video embed field (topic)"](https://docs.google.com/document/d/1WBe3lO-6nPO0i5yfXNNujQMLJ4XGEui3Plh4bcAJwDk/edit#).
- Downloads Video Embed Media, Video Embed Field
- Enables Video Embed Media, Video Embed Field, Entity, Media Entity
- Adds a Video media bundle at http://midcamp.org.docker.amazee.io/admin/structure/media/manage/video
- Adds a video embed field to the Topic node
- Edit a Topic node.  Observe that a video embed field now exists
I added the Video field just below the body, as my assumption is that it will be for the presentation after MidCamp is complete.  It seemed like a logical place to drop the video.
I hid the field label, because it seemed redundant.
=> Video field for Topic nodes

conf/drupal/config/block.block.views_block__jobs_board_block_1.yml, conf/drupal/config/views.view.jobs_board.yml
- Creates a block display on the View `jobs_board` with a contextual filter for Company
- Places block on Sponsor nodes to display the related job listings
- Navigate to a sponsor node with jobs (like [Pantheon](http://midcamp.org.docker.amazee.io/sponsor/pantheon) or [Digital Bridge](http://midcamp.org.docker.amazee.io/sponsor/digital-bridge-solutions)).  Observe that their job nodes are displaying
- Navigate to a sponsor node with no jobs listed (like [MyDropWizard](http://midcamp.org.docker.amazee.io/sponsor/my-drop-wizard)).  Observe that no jobs display
=> Sponsor Jobs Display

web/themes/custom/hatter/hatter.theme
- Adds link class for field_registration_link with preprocess_field function
- `drush cr`
- Visit a [training node](http://midcamp.org.docker.amazee.io/training/git-ur-pro-dev-workflow-and-go-continuous-integration-zero-hero).  Observe the Register Today link is styled as `button--tertiary`.
- Could probably use the [Link Class](https://www.drupal.org/project/link_class) module for easier control of things like this, but in lieu of larger needs beyond this one link I went with preprocessing instead.
I chose `button--tertiary` for the class here, please advise if we need something different.
=> Buttonize the Register Today link on Training nodes

composer.lock
Addresses https://www.drupal.org/SA-CORE-2018-001
- Inside Docker, run `drush updb`.  Observe that Drupal is updated to 8.4.5 and nothing is horribly broken.
Didn't encounter any prompts to rebuild node access locally.
=> Update Drupal core to 8.4.5

conf/drupal/config/core.entity_form_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/field.field.node.topic.field_presenter_slides.yml, conf/drupal/config/field.storage.node.field_presenter_slides.yml
- Adds `field_presenter_slide` to the Topic node type 
- File field
- Limited to PDF, PPT, PPTX file extensions
- Allows for optional display
- Navigate to an existing Topics session.  Add a file in `field_presenter_slide`.  
- Observe it allows uploading of files
- Observe it displays on the front end
- Observe it can be toggled on or off with the "Include file in display" boolean
**Form display**
**Front end display**
- What file formats should be allowed?  I arbitrarily added PDFs and PowerPoint files.
- Should web links (like Google Slides, Reveal JS presentations) be supported?  If so it might be better to refactor this with Media entities.
- If #129 is accepted, suggest we make this field "Private" so only the author (or admins) can edit it.
=> Topic: Presenter slide upload

composer.json, composer.lock, conf/drupal/config/block.block.hatter_content.yml, conf/drupal/config/block.block.hatter_help.yml, conf/drupal/config/block.block.hatter_local_actions.yml, conf/drupal/config/block.block.hatter_messages.yml, conf/drupal/config/block.block.hatter_page_title.yml, conf/drupal/config/block.block.midcamp2019.yml, conf/drupal/config/block.block.tabs.yml, conf/drupal/config/block.block.views_block__event_news_block_1.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_2.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_3.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_4.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_5.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_6.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_7.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_8.yml, conf/drupal/config/block.block.views_block__speakers_block_1.yml, conf/drupal/config/block.block.webform.yml, conf/drupal/config/config_ignore.settings.yml, conf/drupal/config/core.extension.yml, docker-compose.yml
- Updates Docker image to `amazeeio/drupal:php71-basic ` to keep local environments consistent with remotes (remotes were updated to PHP 7.1 on March 28)
- Exports config from production environment (primarily content changes via block placement)
- Downloads the [Config Ignore](https://www.drupal.org/project/config_ignore) module, configured to exclude the MailChimp API (now we don't need to reset this on every `cim`)
- `pygmy restart`
- SSH into the Docker environment.  Confirm PHP 7.1 is installed with `php -v`
- Run `drush cim -y` to import config.  Observe the following:
- Production config is imported/preserved
- Config Ignore module is enabled and configured
- MailChimp API keys are no longer overwritten
=> Update Docker image, export prod config, add config_ignore module

.circleci/config.yml
Circle was failing because of the key `filters` in the `build_and_test` workflow:
This PR removes workflows entirely for now, since we are only building, and not testing.  
Additionally, use the PHP 71 docker image in Circle.
=> Make Circle Work Again

README.md
Per [Amazee's documentation](https://docs.amazee.io/local_docker_development/os_x_cachalot.html), `cachalot` is no longer the preferred method, and support for it will end soon.  [Pygmy](https://docs.amazee.io/local_docker_development/pygmy.html) is now the preferred method, so this PR updates the readme to account for this change.
Follow the instructions in the README to install the site.
=> Update READEME to remove cachalot references, replace with Pygmy.

.lagoon.yml
Reverts MidCamp/midcamp#162.  Taking down the GitHub Pages splash and restoring site to the base domain.
=> Revert "Comment out production domains"

conf/drupal/config/block.block.views_block__event_sponsors_block_2.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_3.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_4.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_5.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_7.yml, conf/drupal/config/block.block.views_block__training_block_1.yml, conf/drupal/config/core.extension.yml, conf/drupal/config/field.field.node.topic.field_event.yml, conf/drupal/config/field.field.node.training.field_event.yml, conf/drupal/config/node.type.page.yml, conf/drupal/config/user.role.authenticated.yml, conf/drupal/config/views.view.event_sponsors.yml, conf/drupal/config/views.view.event_venue.yml, conf/drupal/config/views.view.news.yml, conf/drupal/config/views.view.schedule.yml, conf/drupal/config/views.view.schedule_2019.yml, conf/drupal/config/views.view.sessions.yml, conf/drupal/config/views.view.training.yml, conf/drupal/config/views.view.trainings.yml, web/modules/custom/midcamp_utility/midcamp_utility.info.yml, web/modules/custom/midcamp_utility/midcamp_utility.module, web/themes/custom/hatter/hatter.theme
- Updates News view
- Adds filter to primary display for 2018 content
- Creates second display to show 2019 content
- Adds 2019 display to the "About" menu (consistent with 2018 event IA)
- Updates Venue view
- Adds contextual filter for `event` term ID to show the Venue for the event relative to the page you are viewing
- Creates `midcamp_utility` basic helper module
- Uses `hook_views_pre_view()` to find a term ID to pass to the event view when one is not available (like on Views pages)
- Updates Sponsors view
- Adds contextual filter for `event` term ID to show the sponsors relative to the page
- Updates all Sponsor view blocks to be placed on paths `/*/sponsors`.  Previously was `/2018/sponsors`--now allows for multiple event year sponsor pages
- Updates Schedule view
- Adds 2018 year …
=> News, Venue, Sponsors, Schedule updates

conf/drupal/config/block.block.views_block__event_sponsors_block_1.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_6.yml, conf/drupal/config/block.block.views_block__event_sponsors_block_8.yml, conf/drupal/config/views.view.event_sponsors.yml, web/modules/custom/midcamp_utility/midcamp_utility.module, web/themes/custom/hatter/hatter.theme, web/themes/custom/hatter/templates/user/user--compact.html.twig
- Exports config from `production`
- Updates `midcamp_utility_views_pre_view()` to ensure both `event_venue` and `event_sponsors` views get arguments from URL path if possible, and default to the 2019 event on nodes without events assigned.
- Updates `hatter_preprocess_user()` to get the term name from `field_organization` and passes it to TWIG for rendering (fixes bad links resulting from wrapping `item.content` in a link)
Visit the test environment at https://nginx-midcamp-org-feature-config-views-updates.us.amazee.io.  Verify the following pages are displaying their Venue and Sponsor blocks in the footer:
Visit the [submitted sessions page](https://nginx-midcamp-org-feature-config-views-updates.us.amazee.io/2019/submitted-sessions) and click through to some sessions.  Observe the …
=> Update production config, ensure Sponsor/Venue views get args, fix organization links

conf/drupal/config/core.entity_form_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/field.field.node.topic.field_session_length.yml, conf/drupal/config/field.storage.node.field_session_length.yml
Adds required field "Session Length" to Topic content type.  Available options are `30 minutes` and `60 minutes`.  
Visit https://nginx-midcamp-org-feature-topic-time-field.us.amazee.io/, sign in and attempt to submit a session.  Observe you must select a session length.
=> Add Session Length radio to Topic nodes.

conf/drupal/config/field.field.node.topic.field_topic_type.yml, conf/drupal/config/field.storage.node.field_topic_type.yml
- Defaults `field_topic_type` to "Session" on Topic node type
- Restricts access to `field_topic_type` to administrators so users can't see or change it
- Navigate to https://nginx-midcamp-org-feature-update-topic-content-type.us.amazee.io/
- Log in with a user account without the Administrator role
- Create a Topic node.  Observe you cannot see or change `field_topic_type`
- Log in as an administrator.  Look at the node you previously created and confirm it is set to "Session"
=> Update topic content type

composer.lock, conf/drupal/config/field.storage.node.field_presenter_slides.yml, conf/drupal/config/user.role.anonymous.yml, conf/drupal/config/user.role.authenticated.yml
- Updates Mailchimp module (among other things, was causing errors on field settings saves https://www.drupal.org/project/mailchimp/issues/2949234)
- Sets field permissions for `field_presenter_slides` so only admins can modify
=> Update slides field permissions

conf/drupal/config/system.action.topic_reject.yml, web/modules/custom/midcamp_vbo/config/install/system.action.topic_reject.yml, web/modules/custom/midcamp_vbo/config/schema/midcamp_vbo.schema.yml, web/modules/custom/midcamp_vbo/src/Plugin/Action/TopicReject.php
Adds inverse action to the one provided by `Drupal\midcamp_vbo\Plugin\Action\TopicAcceptConfirm`.
- Visit https://nginx-midcamp-org-feature-vbo-action.us.amazee.io/ 
- Navigate to the content overview page
- Select a confirmed node and use the bulk operations action "Reject or unconfirm topic"
- Observe that the node is no longer accepted
=> Create VBO action to unset field_accepted_confirmed

conf/drupal/config/views.view.summits.yml, conf/drupal/config/views.view.training.yml, web/themes/custom/hatter/hatter.theme
Sets `button--primary` class for registration links on Summit, Training nodes and landing pages.
Visit the following pages, observing the button styles are consistent with the primary button styles in [Hatter](https://midcamp.github.io/Hatter/elements/element-buttons/):
- Summit node
- Summit landing
- Training node
- Training landing
=> Set primary button class for Trainings, Summits.

composer.lock, conf/drupal/config/core.entity_view_display.user.user.schedule.yml, conf/drupal/config/core.entity_view_mode.user.schedule.yml, conf/drupal/config/image.style.schedule_presenter.yml, conf/drupal/config/views.view.schedule_2019.yml, web/themes/custom/hatter/hatter.theme, web/themes/custom/hatter/templates/field/field--user--field-company-logo--schedule.html.twig, web/themes/custom/hatter/templates/field/field--user--field-name--schedule.html.twig, web/themes/custom/hatter/templates/field/field--user--user-picture--schedule.html.twig, web/themes/custom/hatter/templates/user/user--schedule.html.twig
In conjunction with [Style Guide PR 41](https://github.com/MidCamp/Hatter/pull/41), this updates the Schedule display to show speaker images, titles and company logos.  
Changes include:
- Introduction of a `schedule` view mode for `User` entities
- Introduction of a `schedule_presenter` image style to crop an appropriately sized square image (required for the border radius on `.schedule__speaker__photo`)
- Updates to the `schedule_2019` view to use the `schedule` view mode, remove extraneous wrapping divs
- Use `h3` for session titles
- Create new template suggestions for fields on the `schedule` user view mode
- Writes `field_organization` value into the `field_name` template via `hatter_preprocess_field()` to resolve a nagging whitespace issue that should have been easier to resolve in …
=> Update Schedule Display

web/modules/custom/midcamp_utility/midcamp_utility.module
Expands the logic from #186 to include non-event term pages, ensuring the Venue and Sponsor blocks default to the current event year.
=> Ensure other term pages get args for sponsor, venue Views.

composer.json, composer.lock, conf/drupal/config/core.entity_form_display.user.user.default.yml, conf/drupal/config/core.entity_view_display.user.user.default.yml, conf/drupal/config/field.field.user.user.field_organizer_year.yml, conf/drupal/config/field.storage.user.field_organizer_year.yml, conf/drupal/config/views.view.organizers.yml, web/modules/custom/midcamp_utility/midcamp_utility.post_config_import.php, web/themes/custom/hatter/templates/user/user--featured-speaker.html.twig
The existing [Organizers page](https://www.midcamp.org/2018/organizers) Is based on role, which isn't well suited to displaying different organizers over different years.  This PR:
- Adds `field_organizer_year`, an entity reference field to the `event` taxonomy, allowing Users to be tagged as an organizer for a given event
- Implements admin-only permissions on `field_organizer_year` so nobody else can see it or edit its values
- Patches Drupal Core to allow for `hook_post_config_import_NAME()`, which allows you to run arbitrary updates after a config import (see https://www.drupal.org/project/drupal/issues/2901418).  This allows the next step, which is to:
- Assign the value for MidCamp 2018 to all existing users with the Organizer role, reflecting the pattern set last year.  
- Assign …
=> Multi year organizers

conf/drupal/config/block.block.webform.yml
The webform to capture Lightning Talk proposals was previously added to a 2018 node with an outdated alias.  This PR updates that alias, and additionally adds the form to the 2019 topic page for lightning talks.
- Visit the [2018 Lightning Talks topic](http://midcamp.org.docker.amazee.io/2018/topic-proposal/lightning-talks).  Observe the webform displays
- Visit the [2019 Lightning Talks topic](http://midcamp.org.docker.amazee.io/2019/topic-proposal/lightning-talks).  Observe the webform displays
=> Update paths for Lightning Talks webform

conf/drupal/config/views.view.attendees.yml, conf/drupal/config/views.view.news.yml, conf/drupal/config/views.view.organizers.yml, conf/drupal/config/views.view.schedule_2019.yml, conf/drupal/config/views.view.trainings.yml
This PR updates the existing `schedule_2019` View to add a Wednesday page display including `summit` and `training_proposal` nodes tagged with this year's event.
Visit https://nginx-midcamp-org-feature-wednesday-schedule.us.amazee.io/2019/schedule/wednesday
- Navigate to http://midcamp.org.docker.amazee.io/2019/schedule/wednesday.  Observe Trainings and Summits appear here, styled consistently with Session schedule pages.  Observe the navigation at the top of the schedule targets this new page.
Need to update the menu once this is deployed.
~The existing Training View excluded the node "Getting started with the Drupal issue queue."  Is there a reason to exclude this from the View, or can that node simply be unpublished?~ **EDIT:** Filtering this out, …
=> Wednesday schedule

conf/drupal/config/views.view.schedule_2019.yml
PR #228 introduced a regression in the `schedule_2019` view displays for Thursday and Friday sessions whereby the grouping based on `field_schedule_time` was removed.  This PR restores the original grouping, and adds an override for the Wednesday display to allow the Summit & Training schedule to display differently. 
- Navigate to the 2019 schedule.  Observe the Wednesday schedule is grouped by `type` (Summits and Trainings) and the Thursday/Friday schedules are grouped by time
=> Fix 2019 Schedule groupings, override for Wednesday schedule.

conf/drupal/config/views.view.schedule_2019.yml
The [Wednesday schedule](https://www.midcamp.org/2019/schedule/wednesday) was configured to display `summit` and `training` node types, and as a result was not capable of displaying the Wednesday evening social event.  This PR addresses that by:
- Creating a block display on the `schedule_2019` View to query `topic` nodes scheduled on Wednesday
- Updates the Wednesday display of the view to render the new display in the footer
https://nginx-midcamp-org-feature-wednesday-social-schedule.us.amazee.io/2019/schedule/wednesday
- Create a Topic node scheduled on Wednesday evening for the social
- Visit the Wednesday schedule page.  Observe it displays below the rest of the content
The Thurs/Fri schedules don't include any descriptive text, and that pattern …
=> Add a display for Wednesday's social.

conf/drupal/config/field.field.node.job.field_sponsor_company.yml, conf/drupal/config/field.storage.node.field_sponsor_company.yml, conf/drupal/config/views.view.sponsor_company_field_filter.yml, conf/drupal/config/webform.webform.tourism_quote.yml
- Exports prod config update for Tourism webform
- Creates entity reference View to filter sponsors by `Midcamp 2019` event
- Updates `field_sponsor_company` handler on Job content type to use new View to filter companies to this year's sponsors
Alternatively, use the available environment at https://nginx-midcamp-org-feature-update-job-company-filter.us.amazee.io/
=> Update job company filter

conf/drupal/config/block.block.bartik_account_menu.yml, conf/drupal/config/block.block.bartik_footer.yml, conf/drupal/config/block.block.bartik_main_menu.yml, conf/drupal/config/block.block.bartik_tools.yml, conf/drupal/config/block.block.footer.yml, conf/drupal/config/block.block.hatter_account_menu.yml, conf/drupal/config/block.block.hatter_main_menu.yml, conf/drupal/config/block.block.hatter_tools.yml, conf/drupal/config/block.block.midcamp2019navigation.yml, conf/drupal/config/block.block.midcamp2020navigation.yml, conf/drupal/config/system.menu.midcamp-2020-navigation.yml, conf/drupal/config/taxonomy.vocabulary.event.yml, conf/drupal/config/taxonomy.vocabulary.location.yml, conf/drupal/config/taxonomy.vocabulary.organization.yml, conf/drupal/config/taxonomy.vocabulary.session_tracks.yml, conf/drupal/config/taxonomy.vocabulary.sponsor_packages.yml, conf/drupal/config/taxonomy.vocabulary.tags.yml, conf/drupal/config/taxonomy.vocabulary.topic_type.yml, web/themes/custom/hatter/hatter.theme
- Exports some stray production config
- Creates a new menu for 2020 Navigation
- Places that menu everywhere except for `/2018` and `/2019` content.
- Restricts 2019 menu to show on `/2019` pages (was previously everywhere but `/2018`)
- Updates `hatter_theme_suggestions_menu_alter` to let the new menu use the same template as the previous two.
- Navigate to http://midcamp.org.docker.amazee.io/admin/structure/menu/manage/midcamp-2020-navigation
- Add some links
- Look at them from the front end, observe they look/behave as expected.
=> Midcamp 2020 Menu

conf/drupal/config/core.entity_form_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/field.field.node.topic.field_transcript.yml, conf/drupal/config/field.storage.node.field_transcript.yml, conf/drupal/config/user.role.anonymous.yml, conf/drupal/config/user.role.authenticated.yml, conf/drupal/config/user.role.organizer.yml, web/themes/custom/hatter/hatter.theme
- Adds Transcript field to Topic nodes so Sessions can be linked to their video transcripts
- Observe `field_transcript` exists on the `topic` content type
- Observe editing this field is limited to the `organizer` role
- Observe `anonymous` and `authenticated` users can view the field's contents
=> Add Transcript field to Topics.

conf/drupal/config/field.field.node.topic.field_event.yml, conf/drupal/config/user.role.authenticated.yml, features/topic.feature
- Updates default term for `field_event` to "MidCamp 2020"
- Reenable `create topic content` permission for anonymous users so they can submit Topic Proposals
- Adds basic Behat test
=> Open submissions

.circleci/config.yml, Dockerfile.cli
Installs NPM dependencies in `Dockerfile.cli`, since `npm` tooling isn't configured in a Docker container currently.  The `npm install` / `npm ci` commands are not needed  in CI since the Dockerfile handles them--the only reason `composer install` is getting run there is because it is installing dev dependencies to allow Behat testing.
- Run `docker-compose up -d --build`
- Visit http://midcamp.org.docker.amazee.io/admin/appearance and set the Hatter 2019 theme as default
- Observe the theme looks as expected, indicating the `npm ci` task has been performed successfully
- Visit the remote environment corresponding with this PR (https://nginx-midcamp-org-feature-fix-circle.us.amazee.io/) 
- At https://nginx-midcamp-org-feature-fix-circle.us.amazee.io/admin/appearance set the Hatter 2019 …
=> Install NPM dependencies inside the CLI

composer.json, composer.lock
Performs all available updates to contrib modules to prepare for Drupal 8.8/9.  Includes:
- Pathauto
- Admin Toolbar 
- Config Filter
- Config Ignore
- Honeypot
- Metatag
- Token
- Redirect
- Paragraphs
- Simple XML Sitemap
- Webform
Test on https://nginx-midcamp-org-feature-update-pathauto.us.amazee.io/
=> Update contrib modules

conf/drupal/config/core.entity_view_display.user.user.featured_speaker.yml, conf/drupal/config/views.view.organizers.yml, conf/drupal/config/webform.webform.contact.yml, conf/drupal/config/webform.webform.lightning_talk_sign_up.yml, conf/drupal/config/webform.webform.midcamp_2018_survey.yml, conf/drupal/config/webform.webform.midcamp_2019_survey.yml, conf/drupal/config/webform.webform.room_monitor_checklist.yml, conf/drupal/config/webform.webform.session_feedback.yml, conf/drupal/config/webform.webform.tourism_quote.yml, conf/drupal/config/webform.webform.training_feedback.yml, conf/drupal/config/webform.webform.training_feedback_2019.yml
- Creates a 2020 display of the Organizer View
- Links Featured Speaker view mode images to user profiles 
- Visit https://nginx-midcamp-org-feature-organizer-page.us.amazee.io/2020/organizers
- Observe a list of Organizers, like the previous years
- Observe the images link to user profile pages
- Disregard the missing images, they aren't synced to this environment
=> Organizer page 2020

Dockerfile.cli, Dockerfile.php
Updates the site to use PHP 7.3. 
- Visit https://nginx-midcamp-org-feature-php-73.us.amazee.io/admin/reports/status and confirm the site is running PHP 7.3.12
- Browse around and make sure things aren't broken
=> Upgrade to PHP 7.3

conf/drupal/config/block.block.hatter_2019_addajobbutton.yml, conf/drupal/config/block.block.hatter_2019_content.yml, conf/drupal/config/block.block.hatter_2019_eventlabelblock.yml, conf/drupal/config/block.block.hatter_2019_help.yml, conf/drupal/config/block.block.hatter_2019_local_actions.yml, conf/drupal/config/block.block.hatter_2019_messages.yml, conf/drupal/config/block.block.hatter_2019_page_title.yml, conf/drupal/config/block.block.hatter_2019_tabs.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_news_block_1.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_10.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_11.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_3.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_4.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_5.yml, conf/drupal/config/block.block.hatter_2019_views_block__event_sponsors_block_9.yml, conf/drupal/config/block.block.hatter_2019_views_block__speakers_block_1.yml, conf/drupal/config/block.block.hatter_2019_views_block__training_block_1.yml, conf/drupal/config/block.block.hatter_2019_webform.yml, conf/drupal/config/block.block.views_block__random_session_block_1.yml, conf/drupal/config/views.view.random_session.yml
Creates a display to showcase a random 2020 confirmed session with speaker image on the homepage.
https://nginx-midcamp-org-feature-random-session-block.us.amazee.io/
Currently styled after the schedule.  Do we want this to look different?
=> Homepage random session block

conf/drupal/config/views.view.schedule_2020.yml
Adds 2020 schedule
Visit https://nginx-midcamp-org-feature-schedule-2020.us.amazee.io/ and observe the links appearing under the "Schedule" parent menu item.
- Trainings appear at https://nginx-midcamp-org-feature-schedule-2020.us.amazee.io/2020/schedule/wednesday
- Thursday sessions appear at https://nginx-midcamp-org-feature-schedule-2020.us.amazee.io/2020/schedule/thursday
- Friday sessions appear at https://nginx-midcamp-org-feature-schedule-2020.us.amazee.io/2020/schedule/friday
- Contribution day placeholder page at https://nginx-midcamp-org-feature-schedule-2020.us.amazee.io/2020/contribution-day
=> 2020 Schedule

README.md
based on the interaction on MidCamp slack:
dwaynemcdaniel  2:38 PM
question:
Running drush sql-sync @production @self
Hitting this error:
Could not load API JWT Token, error was:                                  [warning]
'lagoon@ssh.lagoon.amazeeio.cloud: Permission denied (publickey).
Error: no alias record could be found for source @production                [error]
2:38
any suggestions?
brian_clement  2:46 PM
@dwaynemcdaniel I htink you need your ssh key added by the Amazee team.
2:47
Are you a member of the Amazee Rocket Chat (https://amazeeio.rocket.chat/group/midcamp)?
dwaynemcdaniel  2:47 PM
no I am not.
2:47
first I have heard of it to be honest
brian_clement  2:47 PM
That is the only way I know to get them to add you, let me see if I can send you an invite there.
=> Updating Troubleshooting around SSH access issue

conf/drupal/config/block.block.views_block__session_feedback_block_1.yml, conf/drupal/config/user.role.authenticated.yml, conf/drupal/config/views.view.session_feedback.yml, conf/drupal/config/webform.webform.session_feedback.yml, web/modules/custom/midcamp_utility/midcamp_utility.module
This creates a new view (that's not super well styled, but it should work for now) to display session feedback on session nodes. The block should only be visible to admins and users listed as speakers on the session.
To test:
- visit http://nginx-midcamp-org-feature-session-feedback.us.amazee.io/2020/topic-proposal/build-it-better-stupid-using-design-systems-scalability as anon and observe there's nothing between the Captions and the footer.
- Submit some feedback.
- login as admin and see the block
- login as a speaker on the node: `drush uli 1366` and observe the block is still there
- login as another user: `drush uli 123` and observe the block is hidden.
To do:
- Getting results to display required giving all Authenticated users "View all webform results" permission. This might... not …
=> Add Session Feedback for speakers

web/themes/custom/hatter_base/templates/field/field--node--field-captions.html.twig
As per [this Slack message](https://midcamp.slack.com/archives/C0C4L7J0N/p1586189697021700), add `tabindex` to the transcript to make it keyboard accessible.
To test:
- visit /2020/topic-proposal/build-it-better-stupid-using-design-systems-scalability
- tab through the page and observe the transcript area is tab-able.
=> Add tabindex to caption field item

composer.json, composer.lock
Replaces independently called out Composer dev dependencies with `drupal/core-dev` for easier updating with Drupal Core.
Run the following commands to confirm preexisting packages are still in place:
- `composer show behat/mink`
- `composer show behat/mink-goutte-driver`
- `composer show composer/composer`
- `composer show drupal/coder`
=> Use drupal/core-dev for dev dependencies 

web/themes/custom/hatter/hatter.theme, web/themes/custom/hatter/templates/block/block--hatter-account-menu.html.twig, web/themes/custom/hatter_2019/templates/block/block--hatter-2019-account-menu.html.twig, web/themes/custom/hatter_base/hatter_base.theme, web/themes/custom/hatter_base/templates/block/block--hatter-account-menu.html.twig
The `<front>` page uses the `site_slogan` to display the camp dates, whereas the region above header spelled this out in hard-coded twig markup.
This PR adds a twig variable `site_slogan` to these block templates and uses that to ensure we aren't hand entering dates in twig moving forward.
- Rebuild caches with `lando drush cr`
- Visit the following pages, and confirm they all show `Midwest Drupal Camp March 24 - 27, 2021`:
- 2021 content: http://midcamp-org.lndo.site/2021/article/midcamp-back-march-24-27-2021
- 2020 content: http://midcamp-org.lndo.site/2020
- 2019 content: http://midcamp-org.lndo.site/2019
=> Update menu block templates for correct camp dates.

web/modules/custom/midcamp_utility/midcamp_utility.module
- Updates `midcamp_utility.module`'s unfortunate instance of hard-coded contextual args to match the current event year's taxonomy term ID.
- Updates the hard-coded term ID controlling the `location` taxonomy's View Mode for virtual event years (which show a View mode containing the link to the room on Zoom or wherever)
Wiki updated at https://github.com/MidCamp/midcamp/wiki/Preparing-MidCamp.org-for-a-new-event-year#custom-code to ensure this doesn't get forgotten if it hasn't been refactored by next time.
- Rebuild caches with `lando drush cr`
- Navigate to a page without contextual args, but with a year-based view, like http://midcamp-org.lndo.site/jobs.  Observe last year's sponsors are no longer displaying
- To test the `location` view mode logic, create a 2021 schedule and add some …
=> Update hard-coded term ID for prior event year.

conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_1.yml, web/modules/custom/midcamp_utility/midcamp_utility.module
- Updates [custom code for targeting a default event tid](https://github.com/MidCamp/midcamp/wiki/Preparing-MidCamp.org-for-a-new-event-year#custom-code) to actually use the correct tid
- Updates the Core Sponsors block to display everywhere (this gets contextual args by year, so there shouldn't be any reason it can't display everywhere)
=> Fix core sponsor block

conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_10.yml, conf/drupal/config/block.block.midcamp2021_2.yml, conf/drupal/config/views.view.sponsor_company_field_filter.yml
Prod config includes:
- Defaulting to latest Event taxonomy term year in `field_sponsor_company` (by way of the View `sponsor_company_field_filter` which provides the filter for this field)
- Disables the MidCamp 2021 teaser block previously present on `<front>`
- Places the Community Sponsors block on the `/2021/sponsors` route
=> Export prod config.

composer.json, composer.lock, conf/drupal/config/webform.webform.contact.yml, conf/drupal/config/webform.webform.lightning_talk_sign_up.yml, conf/drupal/config/webform.webform.midcamp_2018_survey.yml, conf/drupal/config/webform.webform.midcamp_2019_survey.yml, conf/drupal/config/webform.webform.midcamp_2020_survey.yml, conf/drupal/config/webform.webform.midcamp_2021_survey.yml, conf/drupal/config/webform.webform.movie_suggestions.yml, conf/drupal/config/webform.webform.room_monitor_checklist.yml, conf/drupal/config/webform.webform.session_feedback.yml, conf/drupal/config/webform.webform.tourism_quote.yml, conf/drupal/config/webform.webform.training_feedback.yml, conf/drupal/config/webform.webform.training_feedback_2019.yml
Per https://www.drupal.org/sa-contrib-2021-004, upgrades the Webform module and exports updated configuration.
- Install dependencies with `lando composer install`
- Perform database updates with `lando drush updb -y`
- Import configuration with `lando drush cim -y`
- Confirm webform functionality is not impacted
=> Upgrade Webform per SA-CONTRIB-2021-004.

conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_3.yml, conf/drupal/config/block.block.hatter_views_block__event_sponsors_block_9.yml, conf/drupal/config/core.entity_form_display.user.user.default.yml, conf/drupal/config/core.entity_view_display.user.user.compact.yml, conf/drupal/config/core.entity_view_display.user.user.default.yml, conf/drupal/config/core.entity_view_display.user.user.email.yml, conf/drupal/config/core.entity_view_display.user.user.featured_speaker.yml, conf/drupal/config/core.entity_view_display.user.user.schedule.yml, conf/drupal/config/core.entity_view_display.user.user.socials.yml, conf/drupal/config/core.menu.static_menu_link_overrides.yml, conf/drupal/config/field.field.user.user.field_leadership_year.yml, conf/drupal/config/field.storage.user.field_leadership_year.yml, conf/drupal/config/views.view.organizers.yml
[Rearrange Organizer Page #3202165](https://www.drupal.org/project/midcamp/issues/3202165)
- Exports production config
- Adds `field_leadership_year` to the `User` entity.  This is an entity reference field, targeting `event` terms consistent with how `field_organizer_year` is currently configured.
- Adds a Views attachment to the `organizers` View to show Leaders for a given year.
- Updates the `organizers` View to omit users who are both Organizers and Leaders to prevent them from displaying twice
- Import configuration changes with `lando drush cim -y`
- Navigate to http://midcamp-org.lndo.site/admin/people and assign some users the `MidCamp 2021` value in `field_leadership_year`
- Navigate to http://midcamp-org.lndo.site/2021/organizers.  Observe these users appear in the upper …
=> #3202165 Organizer Page updates

web/themes/custom/hatter/hatter.libraries.yml, web/themes/custom/hatter/port-to-hatter-v2.css
This is a really hacky fix, but I haven't finished this PR https://github.com/MidCamp/hatter-v2/pull/19 that will allow us to use hatter V2 with the default color scheme. Rather than touch the original Hatter, I created a css file with this fix that makes it clear that it will need to be ported in the future. Perfectly reasonable fix for a week out from camp :)
=> Quick fix for sponsor images being cut off

conf/drupal/config/core.entity_form_display.paragraph.view.default.yml, conf/drupal/config/field.field.paragraph.view.field_view.yml, conf/drupal/config/field.storage.paragraph.field_view.yml
Allows Views to be embedded in Paragraphs.
- Updates Paragraph type `view` form display (at `/admin/structure/paragraphs_type/view/form-display`) to enable the "View" field (previously disabled entirely, leaving no fields present here at all).
- Updates Paragraph type `view` `field_view` settings to allow referencing both Block as well as Page View displays
(Optionally test this here: https://nginx.feature-fix-views-paragraphs.midcamp-org.us2.amazee.io/2021/building-community-day, but note the schedule for 2021 does not have published content to support it)
- Import configuration with `lando drush cim -y`
- Navigate to a basic page node add/edit form
- Click "Add View" in the Paragraph field.  Observe you now have an autocomplete field to specify the View you are trying to embed.
=> Fix Views Paragraphs

web/modules/custom/midcamp_utility/midcamp_utility.module, web/themes/custom/hatter/hatter.theme, web/themes/custom/hatter/templates/term/taxonomy-term--location--topic-page.html.twig, web/themes/custom/hatter/templates/term/taxonomy-term--location.html.twig
Satisfies https://www.drupal.org/project/midcamp/issues/3204814.
Back-ports the logic in #340 to the legacy Hatter theme, which is seeing life once more in 2021.
- Rebuild caches with `lando drush cr`
- Assign a 2021 Topic Proposal node (like http://midcamp-org.lndo.site/2021/topic-proposal/drupal-core-testing-nightwatch-getting-and-running) a "Location" term.  Observe:
- If the Location term has no link, the Topic node will display the room name
- If the Location term has a link, the Topic node will display a button to visit that link
=> #3204814: Backport schedule linking to Hatter theme.

conf/drupal/config/block.block.midcamp2021_3.yml, conf/drupal/config/block.block.midcamp2021survey.yml, conf/drupal/config/block.block.views_block__live_sessions_block_1_2.yml, conf/drupal/config/views.view.live_sessions.yml, conf/drupal/config/webform.webform.midcamp_2021_feedback_survey.yml
Adds the Live Sessions homepage block from last year (see #344) to this year's homepage.
- Import configuration with `lando drush cim -y`
- Change some 2021 Topic nodes to be scheduled right now in your local
- Go to the front page and observe they are appearing there.
=> 2021 Live Sessions homepage block.

composer.json, composer.lock, conf/drupal/config/core.extension.yml, conf/drupal/config/upgrade_status.settings.yml
Adds and enables the Upgrade Status module.  Also updates Drupal Console and some of its dependencies, which were sufficiently outdated that they were preventing the installation of Upgrade Status.
- Install dependencies with `lando composer install`
- Import configuration with `lando drush cim -y`
- Visit [`/admin/reports/upgrade-status`](http://midcamp-org.lndo.site/admin/reports/upgrade-status) and observe the Upgrade Status module is enabled
=> Upgrade Status

.lando.yml, Dockerfile.cli, composer.json, composer.lock
- Updates Composer to version 2
- Set in Dockerfile.cli via `selfupdate` command.  Per https://github.com/uselagoon/lagoon-images/issues/265 this is the recommended path at this time.
- Targeted in `.lando.yml` file via `/usr/local/bin/composer` to prevent locally installed versions (which may still be on Composer 1) from being inadvertently used in local development
- Per https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2, updates the following packages in preparation for Composer 2:
- composer/installers
- cweagans/composer-patches
- oomphinc/composer-installers-extender
- drupal/console (specifically for drupal/console-extend-plugin)
- Updates `drupal/switch_page_theme` to the latest commit in `dev` for D9 support (removing patch that no longer …
=> Composer 2

web/sites/default/all.settings.php
[#3252659 Correct deprecated use of $config_directories in settings.php](https://www.drupal.org/project/midcamp/issues/3252659)
Per https://www.drupal.org/node/3018145, `$config_directories['sync']` has become deprecated, to be replaced by syntax like `$settings['config_sync_directory']`.
- Rebuild caches with `lando drush cr`
- Visit the Upgrade Status report at http://midcamp-org.lndo.site/admin/reports/upgrade-status.  Observe the `Use of $config_directories in settings.php is deprecated.` requirement shows a green status.
- Attempt to export and import configuration.  Observe that this is successful.
=> 3252659: Correct config directory syntax.

composer.json, composer.lock, conf/drupal/config/webform.settings.yml, conf/drupal/config/webform.webform.contact.yml, conf/drupal/config/webform.webform.lightning_talk_sign_up.yml, conf/drupal/config/webform.webform.midcamp_2018_survey.yml, conf/drupal/config/webform.webform.midcamp_2019_survey.yml, conf/drupal/config/webform.webform.midcamp_2020_survey.yml, conf/drupal/config/webform.webform.midcamp_2021_feedback_survey.yml, conf/drupal/config/webform.webform.midcamp_2021_survey.yml, conf/drupal/config/webform.webform.movie_suggestions.yml, conf/drupal/config/webform.webform.room_monitor_checklist.yml, conf/drupal/config/webform.webform.session_feedback.yml, conf/drupal/config/webform.webform.tourism_quote.yml, conf/drupal/config/webform.webform.training_feedback.yml, conf/drupal/config/webform.webform.training_feedback_2019.yml
Updates Webform module to 6.1.2 to satisfy https://www.drupal.org/sa-contrib-2021-045.  Also (incidentally) provides Drupal 9 support.
- Install updated dependencies via `lando composer install`
- Perform database updates via `lando drush updb -y`
- Import updated configuration via `lando drush updb -y`
- Test some webforms, confirm they still function as expected
=> Webform SA-CONTRIB-2021-045

composer.json, composer.lock
Picks up where #437 left off.  That PR disabled config_installer and switched the installation profile to minimal.  Now that this has happened, the actual module can be uninstalled.
- Run `lando composer install`
- Visit http://midcamp-org.lndo.site/admin/reports/upgrade-status
- Confirm Config Installer is no longer listed
- Confirm Devel is no longer listed
=> 3252663: Remove disused modules part 2

Dockerfile.cli, composer.json, composer.lock, patches/mailchimp-prevent-wsod-missing-keys.patch, web/modules/custom/midcamp_event_label_block/midcamp_event_label_block.info.yml, web/modules/custom/midcamp_migration/midcamp_migration.info.yml, web/modules/custom/midcamp_tito/midcamp_tito.info.yml, web/modules/custom/midcamp_utility/midcamp_utility.info.yml, web/modules/custom/midcamp_vbo/midcamp_vbo.info.yml, web/themes/custom/hatter/hatter.info.yml, web/themes/custom/hatter_2019/hatter_2019.info.yml, web/themes/custom/hatter_base/hatter_base.info.yml
- Updates the following modules for D9 compliance:
- Twig Extensions
- R4032login
- Eventbrite Events
- Patches MailChimp module to spare ourselves WSOD pain in lower environments where API keys may be missing
- Update's Lagoon's CLI Dockerfile to ensure patch files local to our repo exist, and also uses their new namespacing for Docker images
We need to get upgraded to Drupal 9.  This has taken an embarrassingly long time.
1. Install updated dependencies via `lando composer install`
2. Perform database updates via `lando drush updb -y`
3. Test the site, make sure it isn't broken
=> 3252658: Additional D9 module upgrades

.ddev/config.yaml, .gitpod.yml, .lagoon.yml, README.md, web/sites/default/settings.php
Getting started... here's how I got here:
- https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#gitpod option 1
- change php version to 7.4
- ddev start
- ddev composer install
- got drupal install!
- https://ddev.readthedocs.io/en/latest/users/providers/lagoon/?h=lagoon
- ddev config --web-environment-add="LAGOON_PROJECT=midcamp-org,LAGOON_ENVIRONMENT=production
- ddev start
- a whole bunch of ssh stuff to add a key to gitpod
- ddev pull lando ~fails~ success!
`ddev pull lagoon` is failing. Asked about it here:
https://discord.com/channels/664580571770388500/1130647712942014604/1173466093646532619
=> Initial ddev config

conf/drupal/config/core.entity_view_display.node.summit.default.yml, conf/drupal/config/core.entity_view_display.node.topic.default.yml, conf/drupal/config/core.entity_view_display.node.topic.full.yml, conf/drupal/config/core.entity_view_display.node.training.default.yml, web/modules/custom/midcamp_utility/src/Plugin/Field/FieldFormatter/BypassAccessEntityReferenceFormatter.php
I couldn't get the site to install using `drush si --existing-config`. So I manually updated a few entity view displays to use the formatter. I could not manually test.
=> Allow rendering referenced users without elevated permissions

.ddev/config.yaml, Dockerfile.cli
Amazee was using node 10. That's real old. Let's update it.
=> fix: Update node version

docker-compose.yml
Amazee builds are throwing a warning:
```
>> Lagoon detected deprecated images during the build
This indicates that an image you're using in the build has been flagged as deprecated.
You should stop using these images as soon as possible.
If the deprecated image has a suggested replacement, it will be mentioned in the warning.
Please visit https://docs.lagoon.sh/deprecated-images for more information.
>> The image (or an image used in the build for) amazeeio/solr:6.6-drupal has been deprecated, marked endoflife
A suggested replacement image is uselagoon/solr-9-drupal
```
we're not using solr at the moment (afaik, unless there's some dark magic involved that doesn't use search_api), so just commenting out the image for now.
=> Stop building solr to snuff the warnings since we're not using it
